<template>
  <v-container
  id="report"
  fluid
  tag="section"
  >
    <v-row>
        <v-col
          cols="12"
          md="10"
        >
          <v-calendar></v-calendar>
        </v-col>
        <v-col
          cols="12"
          md="2"
        >
        </v-col>
    </v-row>
  </v-container>
</template>
